### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by dthiex** [Open-EO/openeo-sentinelhub-python-driver#39]
Nice implementation of this can be found in the VITO backend: https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/CHANGELOG.md

Main advantages I see in this is higher transparency for the user and 1 go to place to see when a certain feature/update was done.

**Comment by dthiex** [comment]
@zansinergise I was thinking of something like below but just when I finished though that tags descriptions on github can serve the exact same purpose so don't think a separate file for this is actually needed. What do you think?

```md
# Changelog
All notable changes to this project will be documented in this file.

This project relies on continuous integration for new features. So we do not yet have explicitly versioned
releases. Releases are simply built continuously, automatically tested, deployed to a [development environment](https://openeo-dev.sinergise.com/testing) and then to [production](https://openeo.sentinel-hub.com/production/).

Note that the openEO API provides a way to support stable and unstable versions in the same implementation:
https://openeo.org/documentation/1.0/developers/api/reference.html#operation/connect

If needed, feature flags are used to allow testing unstable features in development/production,
without compromising stable operations.

## v1.0.10

### Feature
- add skysat commercial data collection to `/collections` endpoint
- support new rate limiting on all 3 deployments ([#25](https://github.com/Open-EO/openeo-sentinelhub-python-driver/issues/25))

### Bugfix
- fix failing update of batch job metadata (`/jobs/{job id}`)

## v1.0.9

### Feature
- add job title as `title` to `properties` field in `/jobs/{job id}/results` response (and batch job metadata)

### Changed
- move `processing:expression` to `properties` field in `/jobs/{job id}/results` response (and batch job metadata) instead of being the top level field

## v1.0.8

### Feature
- add signed url to metadata in links instead of assets in response to `/jobs/{job id}/results`
```

**Comment by zansinergise** [comment]
> @zansinergise I was thinking of something like below but just when I finished though that tags descriptions on github can serve the exact same purpose so don't think a separate file for this is actually needed. What do you think?

@dthiex I like the idea, although in tags you can have additional vX.Y.Z-rc.W tags, which are usually not that relevant and can add to the mess, but still, having an additional file with the recap of changes is just another layer of work, since we anyway describe each tag and which changes it contains -> I would just stick with describing the tags.

**Comment by dthiex** [comment]
Actually meant to tag Žiga 🤦 Anyway it seems tags will work and should get me what I wanted to let's continue using those.

Example of the openEO API specs which has a nice changelog in their releases: https://github.com/Open-EO/openeo-api/releases

**Comment by zcernigoj** [comment]
The tags imported from gitlab have the additional content e.g. https://github.com/Open-EO/openeo-sentinelhub-python-driver/releases/tag/v1.0.8

The tags created in github don't have those (since github doesn't have the same UI as gitlab to set the additional content for tags) - there are releases instead 
https://github.com/Open-EO/openeo-sentinelhub-python-driver/releases

Not optimal, but probably ok

Edit: ah I see that clicking on the tag (imported from gitlab or created in github) sends you to the "same" page with the "same" content (tag + additional content visible)

**Comment by dthiex** [comment]
> Not optimal, but probably ok

Yes, I think it's okay (we should just make sure we create proper release notes).
